### ISSUE TITLE
Unify way in which we store information about Experiment State

### ISSUE THREAD

**Issue by SebChw** [SebChw/Actually-Robust-Training#61]
Currently there are 2 sources of information about state of the experiment.
* Singleton in `experiment_state.py`
* self.state in Experiment class inside `Experiment.py`

Both were created for different use case.

ExperimentState is mainly used within `metric_calculator.py`. As this class needs to know at which step and stage (training, validation) we are currently at to log metrics correctly.

`self.state` contains more local information on which steps has been already done and which is the last one.

Acceptance criteria:
- [ ] List of all potential things that may be usefull in the Experiment state.
- [ ] List of all potential objects that may be dependent on some information stored in the Experiment State.
- [ ] Note on pros and cons on creating one singleton that contains a state of currently run experiment 
- [ ] Note on pros and cons on keeping everyhitng withing `Experiment` object
- [ ] None on pros and cons on having 2 separate classes.
- [ ] Implementation of the best solution from considered above

**Comment by trebacz626** [comment]
###  List of all potential things that may be useful in the Experiment state:
- Currently run step and stage
- list/dictionary of steps run until now (so that steps can get each others results) like a history
- state
### List of all potential objects that may be dependent on some information stored in the Experiment State.
- Metric Calculator
- Experiment
- Dashboard should know the state
- Steps get a list of previously run steps, but they get them through experiment so they do not have to see it
### Note on pros and cons on creating one singleton that contains a state of currently run experiment
Pros:
We can easily access it from anywhere
Cons:
same, so we need to be careful how and where we call it

The state should be saved to a file anyway (that is my opinion) so if we treat it as a module to modify a given file i think it is ok
### Note on pros and cons on keeping everyhitng withing Experiment object
Pros:
- it is "cleaner"
- Experiment state in experiment state sounds good
- Easier to maintain and track dependencies
Cons:
We need to pass it somehow to metric calculator... but we can decorate experiment with metric calculator, can't we?
