### ISSUE TITLE
Add verbose levels

### ISSUE THREAD

**Issue by kordc** [SebChw/Actually-Robust-Training#67]
As @SebChw wrote in [tutorial](https://github.com/SebChw/art_template/blob/mnist_tutorial_cookiecutter/%7B%7Bcookiecutter.project_slug%7D%7D/exp1/tutorial.ipynb) it'd be good to add levels of suppressing some outputs of our experiments' runs. 

I'd suggest adding verbose levels, each skipping another amount of outputs. See how other libs are doing it

**Comment by kordc** [comment]
Comment from the tutorial mentioned above:
`One solution is logging.getLogger("lightning.pytorch.utilities.rank_zero").setLevel(logging.WARNING) etc.`

**Comment by SebChw** [comment]
Check how cumbersome is to ignore these 
![image](https://github.com/SebChw/art/assets/66476124/bddfe37a-c16c-4651-a7b0-621b4461ef21)

**Comment by SebChw** [comment]
If possible add flag ignore_warnings to step, after step logs should be supressed anymore

**Comment by kordc** [comment]
Check also these ones, the model itself could just have an option for verbosity

![image](https://github.com/SebChw/art/assets/72265576/bf801070-ee96-49ce-b080-26ef49c1112c)

**Comment by mmaecki** [comment]
After hours of testing different approaches I've came to the conclusion it is to much work for small "reward".
None of the solutions mentioned here https://github.com/Lightning-AI/lightning/issues/2332 works.

Resonable and robust approach wolud be to initialize trainer in "with outputFilter:" clause, redirect stdout to outputFilter, filter the output and pass it to stdout. However this should be done separately in every step wich is quite a challenge since trainers are initialized differently between the steps.
For now, the issue will not be solved.
